name: deploy

on:
  push:
    branches:
      - 'master'

jobs:
  merge:
    steps:
      - uses: actions/checkout@v2
      - name: Merge
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff master -m "Auto-merge master back to dev"
          git push